import Head from 'next/head'
import Image from 'next/image'
import { Banner } from '../components/Banner';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { SwiperBestRestaurants } from '../components/SwiperBestRestaurants';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <Banner />
        <SwiperBestRestaurants title={''} />
      </main>
      <Footer />
    </div>
  )
}
